#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

use Web::Query;
use JSON;

my $results;

while (<>) {
  next if /^#/;
  chomp;
  my $url = $_;

  my $q = wq($_)->find('link[rel="stylesheet"]');

  my $ver;

  $q->each(sub {
    my $href = $_->attr('href');
    return unless $href =~ /bootstrap\.(min\.)?css/;
    ($ver) = $href =~ /(\d+\.\d+\.\d+)/;
    $ver //= '0.0.0';
  });

  push @{$results->{$ver}}, $url;
}

say JSON->new->pretty->encode($results);

