#!/usr/bin/perl

use strict;
use warnings;

use JSON;
use Path::Tiny;
use Template;

my $json = path('bs.json')->slurp;
my $data = JSON->new->decode($json);

my $versions;

for (@$data) {
  push @{$versions->{$_->{version}}}, $_->{url};
}

my $ver;
for (sort { $b cmp $a } keys %$versions) {
  push @$ver, {
    version => $_,
    urls    => $versions->{$_},
  }
}

my $tt = Template->new({
  INCLUDE_PATH => 'src',
  OUTPUT_PATH  => 'docs',
});

$tt->process('index.html.tt', { versions => $ver }, 'index.md')
  or die Template->error;

